# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /apps/deepblue/bin/cmake

# The command to remove a file.
RM = /apps/deepblue/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangy/Project/deepblue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangy/Project/deepblue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/apps/deepblue/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/apps/deepblue/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangy/Project/deepblue/CMakeFiles /home/zhangy/Project/deepblue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangy/Project/deepblue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named deepblue

# Build rule for target.
deepblue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deepblue
.PHONY : deepblue

# fast build rule for target.
deepblue/fast:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/build
.PHONY : deepblue/fast

#=============================================================================
# Target rules for targets named test_node

# Build rule for target.
test_node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_node
.PHONY : test_node

# fast build rule for target.
test_node/fast:
	$(MAKE) -f CMakeFiles/test_node.dir/build.make CMakeFiles/test_node.dir/build
.PHONY : test_node/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

deepblue/address.o: deepblue/address.cc.o

.PHONY : deepblue/address.o

# target to build an object file
deepblue/address.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/address.cc.o
.PHONY : deepblue/address.cc.o

deepblue/address.i: deepblue/address.cc.i

.PHONY : deepblue/address.i

# target to preprocess a source file
deepblue/address.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/address.cc.i
.PHONY : deepblue/address.cc.i

deepblue/address.s: deepblue/address.cc.s

.PHONY : deepblue/address.s

# target to generate assembly for a file
deepblue/address.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/address.cc.s
.PHONY : deepblue/address.cc.s

deepblue/bytearray.o: deepblue/bytearray.cc.o

.PHONY : deepblue/bytearray.o

# target to build an object file
deepblue/bytearray.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/bytearray.cc.o
.PHONY : deepblue/bytearray.cc.o

deepblue/bytearray.i: deepblue/bytearray.cc.i

.PHONY : deepblue/bytearray.i

# target to preprocess a source file
deepblue/bytearray.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/bytearray.cc.i
.PHONY : deepblue/bytearray.cc.i

deepblue/bytearray.s: deepblue/bytearray.cc.s

.PHONY : deepblue/bytearray.s

# target to generate assembly for a file
deepblue/bytearray.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/bytearray.cc.s
.PHONY : deepblue/bytearray.cc.s

deepblue/config.o: deepblue/config.cc.o

.PHONY : deepblue/config.o

# target to build an object file
deepblue/config.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/config.cc.o
.PHONY : deepblue/config.cc.o

deepblue/config.i: deepblue/config.cc.i

.PHONY : deepblue/config.i

# target to preprocess a source file
deepblue/config.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/config.cc.i
.PHONY : deepblue/config.cc.i

deepblue/config.s: deepblue/config.cc.s

.PHONY : deepblue/config.s

# target to generate assembly for a file
deepblue/config.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/config.cc.s
.PHONY : deepblue/config.cc.s

deepblue/env.o: deepblue/env.cc.o

.PHONY : deepblue/env.o

# target to build an object file
deepblue/env.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/env.cc.o
.PHONY : deepblue/env.cc.o

deepblue/env.i: deepblue/env.cc.i

.PHONY : deepblue/env.i

# target to preprocess a source file
deepblue/env.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/env.cc.i
.PHONY : deepblue/env.cc.i

deepblue/env.s: deepblue/env.cc.s

.PHONY : deepblue/env.s

# target to generate assembly for a file
deepblue/env.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/env.cc.s
.PHONY : deepblue/env.cc.s

deepblue/fd_manager.o: deepblue/fd_manager.cc.o

.PHONY : deepblue/fd_manager.o

# target to build an object file
deepblue/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fd_manager.cc.o
.PHONY : deepblue/fd_manager.cc.o

deepblue/fd_manager.i: deepblue/fd_manager.cc.i

.PHONY : deepblue/fd_manager.i

# target to preprocess a source file
deepblue/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fd_manager.cc.i
.PHONY : deepblue/fd_manager.cc.i

deepblue/fd_manager.s: deepblue/fd_manager.cc.s

.PHONY : deepblue/fd_manager.s

# target to generate assembly for a file
deepblue/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fd_manager.cc.s
.PHONY : deepblue/fd_manager.cc.s

deepblue/fiber.o: deepblue/fiber.cc.o

.PHONY : deepblue/fiber.o

# target to build an object file
deepblue/fiber.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fiber.cc.o
.PHONY : deepblue/fiber.cc.o

deepblue/fiber.i: deepblue/fiber.cc.i

.PHONY : deepblue/fiber.i

# target to preprocess a source file
deepblue/fiber.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fiber.cc.i
.PHONY : deepblue/fiber.cc.i

deepblue/fiber.s: deepblue/fiber.cc.s

.PHONY : deepblue/fiber.s

# target to generate assembly for a file
deepblue/fiber.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/fiber.cc.s
.PHONY : deepblue/fiber.cc.s

deepblue/hook.o: deepblue/hook.cc.o

.PHONY : deepblue/hook.o

# target to build an object file
deepblue/hook.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/hook.cc.o
.PHONY : deepblue/hook.cc.o

deepblue/hook.i: deepblue/hook.cc.i

.PHONY : deepblue/hook.i

# target to preprocess a source file
deepblue/hook.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/hook.cc.i
.PHONY : deepblue/hook.cc.i

deepblue/hook.s: deepblue/hook.cc.s

.PHONY : deepblue/hook.s

# target to generate assembly for a file
deepblue/hook.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/hook.cc.s
.PHONY : deepblue/hook.cc.s

deepblue/http/http.o: deepblue/http/http.cc.o

.PHONY : deepblue/http/http.o

# target to build an object file
deepblue/http/http.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http.cc.o
.PHONY : deepblue/http/http.cc.o

deepblue/http/http.i: deepblue/http/http.cc.i

.PHONY : deepblue/http/http.i

# target to preprocess a source file
deepblue/http/http.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http.cc.i
.PHONY : deepblue/http/http.cc.i

deepblue/http/http.s: deepblue/http/http.cc.s

.PHONY : deepblue/http/http.s

# target to generate assembly for a file
deepblue/http/http.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http.cc.s
.PHONY : deepblue/http/http.cc.s

deepblue/http/http_connection.o: deepblue/http/http_connection.cc.o

.PHONY : deepblue/http/http_connection.o

# target to build an object file
deepblue/http/http_connection.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_connection.cc.o
.PHONY : deepblue/http/http_connection.cc.o

deepblue/http/http_connection.i: deepblue/http/http_connection.cc.i

.PHONY : deepblue/http/http_connection.i

# target to preprocess a source file
deepblue/http/http_connection.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_connection.cc.i
.PHONY : deepblue/http/http_connection.cc.i

deepblue/http/http_connection.s: deepblue/http/http_connection.cc.s

.PHONY : deepblue/http/http_connection.s

# target to generate assembly for a file
deepblue/http/http_connection.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_connection.cc.s
.PHONY : deepblue/http/http_connection.cc.s

deepblue/http/http_parser.o: deepblue/http/http_parser.cc.o

.PHONY : deepblue/http/http_parser.o

# target to build an object file
deepblue/http/http_parser.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_parser.cc.o
.PHONY : deepblue/http/http_parser.cc.o

deepblue/http/http_parser.i: deepblue/http/http_parser.cc.i

.PHONY : deepblue/http/http_parser.i

# target to preprocess a source file
deepblue/http/http_parser.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_parser.cc.i
.PHONY : deepblue/http/http_parser.cc.i

deepblue/http/http_parser.s: deepblue/http/http_parser.cc.s

.PHONY : deepblue/http/http_parser.s

# target to generate assembly for a file
deepblue/http/http_parser.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_parser.cc.s
.PHONY : deepblue/http/http_parser.cc.s

deepblue/http/http_server.o: deepblue/http/http_server.cc.o

.PHONY : deepblue/http/http_server.o

# target to build an object file
deepblue/http/http_server.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_server.cc.o
.PHONY : deepblue/http/http_server.cc.o

deepblue/http/http_server.i: deepblue/http/http_server.cc.i

.PHONY : deepblue/http/http_server.i

# target to preprocess a source file
deepblue/http/http_server.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_server.cc.i
.PHONY : deepblue/http/http_server.cc.i

deepblue/http/http_server.s: deepblue/http/http_server.cc.s

.PHONY : deepblue/http/http_server.s

# target to generate assembly for a file
deepblue/http/http_server.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_server.cc.s
.PHONY : deepblue/http/http_server.cc.s

deepblue/http/http_session.o: deepblue/http/http_session.cc.o

.PHONY : deepblue/http/http_session.o

# target to build an object file
deepblue/http/http_session.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_session.cc.o
.PHONY : deepblue/http/http_session.cc.o

deepblue/http/http_session.i: deepblue/http/http_session.cc.i

.PHONY : deepblue/http/http_session.i

# target to preprocess a source file
deepblue/http/http_session.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_session.cc.i
.PHONY : deepblue/http/http_session.cc.i

deepblue/http/http_session.s: deepblue/http/http_session.cc.s

.PHONY : deepblue/http/http_session.s

# target to generate assembly for a file
deepblue/http/http_session.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/http_session.cc.s
.PHONY : deepblue/http/http_session.cc.s

deepblue/http/servlet.o: deepblue/http/servlet.cc.o

.PHONY : deepblue/http/servlet.o

# target to build an object file
deepblue/http/servlet.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/servlet.cc.o
.PHONY : deepblue/http/servlet.cc.o

deepblue/http/servlet.i: deepblue/http/servlet.cc.i

.PHONY : deepblue/http/servlet.i

# target to preprocess a source file
deepblue/http/servlet.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/servlet.cc.i
.PHONY : deepblue/http/servlet.cc.i

deepblue/http/servlet.s: deepblue/http/servlet.cc.s

.PHONY : deepblue/http/servlet.s

# target to generate assembly for a file
deepblue/http/servlet.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/servlet.cc.s
.PHONY : deepblue/http/servlet.cc.s

deepblue/http/thirdparty/http_parser.o: deepblue/http/thirdparty/http_parser.c.o

.PHONY : deepblue/http/thirdparty/http_parser.o

# target to build an object file
deepblue/http/thirdparty/http_parser.c.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/thirdparty/http_parser.c.o
.PHONY : deepblue/http/thirdparty/http_parser.c.o

deepblue/http/thirdparty/http_parser.i: deepblue/http/thirdparty/http_parser.c.i

.PHONY : deepblue/http/thirdparty/http_parser.i

# target to preprocess a source file
deepblue/http/thirdparty/http_parser.c.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/thirdparty/http_parser.c.i
.PHONY : deepblue/http/thirdparty/http_parser.c.i

deepblue/http/thirdparty/http_parser.s: deepblue/http/thirdparty/http_parser.c.s

.PHONY : deepblue/http/thirdparty/http_parser.s

# target to generate assembly for a file
deepblue/http/thirdparty/http_parser.c.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/http/thirdparty/http_parser.c.s
.PHONY : deepblue/http/thirdparty/http_parser.c.s

deepblue/iomanager.o: deepblue/iomanager.cc.o

.PHONY : deepblue/iomanager.o

# target to build an object file
deepblue/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/iomanager.cc.o
.PHONY : deepblue/iomanager.cc.o

deepblue/iomanager.i: deepblue/iomanager.cc.i

.PHONY : deepblue/iomanager.i

# target to preprocess a source file
deepblue/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/iomanager.cc.i
.PHONY : deepblue/iomanager.cc.i

deepblue/iomanager.s: deepblue/iomanager.cc.s

.PHONY : deepblue/iomanager.s

# target to generate assembly for a file
deepblue/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/iomanager.cc.s
.PHONY : deepblue/iomanager.cc.s

deepblue/log.o: deepblue/log.cc.o

.PHONY : deepblue/log.o

# target to build an object file
deepblue/log.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/log.cc.o
.PHONY : deepblue/log.cc.o

deepblue/log.i: deepblue/log.cc.i

.PHONY : deepblue/log.i

# target to preprocess a source file
deepblue/log.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/log.cc.i
.PHONY : deepblue/log.cc.i

deepblue/log.s: deepblue/log.cc.s

.PHONY : deepblue/log.s

# target to generate assembly for a file
deepblue/log.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/log.cc.s
.PHONY : deepblue/log.cc.s

deepblue/mutex.o: deepblue/mutex.cc.o

.PHONY : deepblue/mutex.o

# target to build an object file
deepblue/mutex.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/mutex.cc.o
.PHONY : deepblue/mutex.cc.o

deepblue/mutex.i: deepblue/mutex.cc.i

.PHONY : deepblue/mutex.i

# target to preprocess a source file
deepblue/mutex.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/mutex.cc.i
.PHONY : deepblue/mutex.cc.i

deepblue/mutex.s: deepblue/mutex.cc.s

.PHONY : deepblue/mutex.s

# target to generate assembly for a file
deepblue/mutex.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/mutex.cc.s
.PHONY : deepblue/mutex.cc.s

deepblue/scheduler.o: deepblue/scheduler.cc.o

.PHONY : deepblue/scheduler.o

# target to build an object file
deepblue/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/scheduler.cc.o
.PHONY : deepblue/scheduler.cc.o

deepblue/scheduler.i: deepblue/scheduler.cc.i

.PHONY : deepblue/scheduler.i

# target to preprocess a source file
deepblue/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/scheduler.cc.i
.PHONY : deepblue/scheduler.cc.i

deepblue/scheduler.s: deepblue/scheduler.cc.s

.PHONY : deepblue/scheduler.s

# target to generate assembly for a file
deepblue/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/scheduler.cc.s
.PHONY : deepblue/scheduler.cc.s

deepblue/socket.o: deepblue/socket.cc.o

.PHONY : deepblue/socket.o

# target to build an object file
deepblue/socket.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/socket.cc.o
.PHONY : deepblue/socket.cc.o

deepblue/socket.i: deepblue/socket.cc.i

.PHONY : deepblue/socket.i

# target to preprocess a source file
deepblue/socket.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/socket.cc.i
.PHONY : deepblue/socket.cc.i

deepblue/socket.s: deepblue/socket.cc.s

.PHONY : deepblue/socket.s

# target to generate assembly for a file
deepblue/socket.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/socket.cc.s
.PHONY : deepblue/socket.cc.s

deepblue/stream.o: deepblue/stream.cc.o

.PHONY : deepblue/stream.o

# target to build an object file
deepblue/stream.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/stream.cc.o
.PHONY : deepblue/stream.cc.o

deepblue/stream.i: deepblue/stream.cc.i

.PHONY : deepblue/stream.i

# target to preprocess a source file
deepblue/stream.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/stream.cc.i
.PHONY : deepblue/stream.cc.i

deepblue/stream.s: deepblue/stream.cc.s

.PHONY : deepblue/stream.s

# target to generate assembly for a file
deepblue/stream.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/stream.cc.s
.PHONY : deepblue/stream.cc.s

deepblue/streams/socket_stream.o: deepblue/streams/socket_stream.cc.o

.PHONY : deepblue/streams/socket_stream.o

# target to build an object file
deepblue/streams/socket_stream.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/streams/socket_stream.cc.o
.PHONY : deepblue/streams/socket_stream.cc.o

deepblue/streams/socket_stream.i: deepblue/streams/socket_stream.cc.i

.PHONY : deepblue/streams/socket_stream.i

# target to preprocess a source file
deepblue/streams/socket_stream.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/streams/socket_stream.cc.i
.PHONY : deepblue/streams/socket_stream.cc.i

deepblue/streams/socket_stream.s: deepblue/streams/socket_stream.cc.s

.PHONY : deepblue/streams/socket_stream.s

# target to generate assembly for a file
deepblue/streams/socket_stream.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/streams/socket_stream.cc.s
.PHONY : deepblue/streams/socket_stream.cc.s

deepblue/tcp_server.o: deepblue/tcp_server.cc.o

.PHONY : deepblue/tcp_server.o

# target to build an object file
deepblue/tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/tcp_server.cc.o
.PHONY : deepblue/tcp_server.cc.o

deepblue/tcp_server.i: deepblue/tcp_server.cc.i

.PHONY : deepblue/tcp_server.i

# target to preprocess a source file
deepblue/tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/tcp_server.cc.i
.PHONY : deepblue/tcp_server.cc.i

deepblue/tcp_server.s: deepblue/tcp_server.cc.s

.PHONY : deepblue/tcp_server.s

# target to generate assembly for a file
deepblue/tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/tcp_server.cc.s
.PHONY : deepblue/tcp_server.cc.s

deepblue/thread.o: deepblue/thread.cc.o

.PHONY : deepblue/thread.o

# target to build an object file
deepblue/thread.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/thread.cc.o
.PHONY : deepblue/thread.cc.o

deepblue/thread.i: deepblue/thread.cc.i

.PHONY : deepblue/thread.i

# target to preprocess a source file
deepblue/thread.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/thread.cc.i
.PHONY : deepblue/thread.cc.i

deepblue/thread.s: deepblue/thread.cc.s

.PHONY : deepblue/thread.s

# target to generate assembly for a file
deepblue/thread.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/thread.cc.s
.PHONY : deepblue/thread.cc.s

deepblue/timer.o: deepblue/timer.cc.o

.PHONY : deepblue/timer.o

# target to build an object file
deepblue/timer.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/timer.cc.o
.PHONY : deepblue/timer.cc.o

deepblue/timer.i: deepblue/timer.cc.i

.PHONY : deepblue/timer.i

# target to preprocess a source file
deepblue/timer.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/timer.cc.i
.PHONY : deepblue/timer.cc.i

deepblue/timer.s: deepblue/timer.cc.s

.PHONY : deepblue/timer.s

# target to generate assembly for a file
deepblue/timer.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/timer.cc.s
.PHONY : deepblue/timer.cc.s

deepblue/uri.o: deepblue/uri.cc.o

.PHONY : deepblue/uri.o

# target to build an object file
deepblue/uri.cc.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/uri.cc.o
.PHONY : deepblue/uri.cc.o

deepblue/uri.i: deepblue/uri.cc.i

.PHONY : deepblue/uri.i

# target to preprocess a source file
deepblue/uri.cc.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/uri.cc.i
.PHONY : deepblue/uri.cc.i

deepblue/uri.s: deepblue/uri.cc.s

.PHONY : deepblue/uri.s

# target to generate assembly for a file
deepblue/uri.cc.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/uri.cc.s
.PHONY : deepblue/uri.cc.s

deepblue/util.o: deepblue/util.cpp.o

.PHONY : deepblue/util.o

# target to build an object file
deepblue/util.cpp.o:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/util.cpp.o
.PHONY : deepblue/util.cpp.o

deepblue/util.i: deepblue/util.cpp.i

.PHONY : deepblue/util.i

# target to preprocess a source file
deepblue/util.cpp.i:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/util.cpp.i
.PHONY : deepblue/util.cpp.i

deepblue/util.s: deepblue/util.cpp.s

.PHONY : deepblue/util.s

# target to generate assembly for a file
deepblue/util.cpp.s:
	$(MAKE) -f CMakeFiles/deepblue.dir/build.make CMakeFiles/deepblue.dir/deepblue/util.cpp.s
.PHONY : deepblue/util.cpp.s

examples/echo_server.o: examples/echo_server.cc.o

.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.cc.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.o
.PHONY : examples/echo_server.cc.o

examples/echo_server.i: examples/echo_server.cc.i

.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.cc.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.i
.PHONY : examples/echo_server.cc.i

examples/echo_server.s: examples/echo_server.cc.s

.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.cc.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.s
.PHONY : examples/echo_server.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http.o: tests/test_http.cc.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cc.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.o
.PHONY : tests/test_http.cc.o

tests/test_http.i: tests/test_http.cc.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cc.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.i
.PHONY : tests/test_http.cc.i

tests/test_http.s: tests/test_http.cc.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cc.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.s
.PHONY : tests/test_http.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_node.o: tests/test_node.cc.o

.PHONY : tests/test_node.o

# target to build an object file
tests/test_node.cc.o:
	$(MAKE) -f CMakeFiles/test_node.dir/build.make CMakeFiles/test_node.dir/tests/test_node.cc.o
.PHONY : tests/test_node.cc.o

tests/test_node.i: tests/test_node.cc.i

.PHONY : tests/test_node.i

# target to preprocess a source file
tests/test_node.cc.i:
	$(MAKE) -f CMakeFiles/test_node.dir/build.make CMakeFiles/test_node.dir/tests/test_node.cc.i
.PHONY : tests/test_node.cc.i

tests/test_node.s: tests/test_node.cc.s

.PHONY : tests/test_node.s

# target to generate assembly for a file
tests/test_node.cc.s:
	$(MAKE) -f CMakeFiles/test_node.dir/build.make CMakeFiles/test_node.dir/tests/test_node.cc.s
.PHONY : tests/test_node.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcp_server.o: tests/test_tcp_server.cc.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.o
.PHONY : tests/test_tcp_server.cc.o

tests/test_tcp_server.i: tests/test_tcp_server.cc.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.i
.PHONY : tests/test_tcp_server.cc.i

tests/test_tcp_server.s: tests/test_tcp_server.cc.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.s
.PHONY : tests/test_tcp_server.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_tcp_server"
	@echo "... edit_cache"
	@echo "... test_http_parser"
	@echo "... test_bytearray"
	@echo "... test_http"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... test_socket"
	@echo "... test_thread"
	@echo "... deepblue"
	@echo "... test_node"
	@echo "... test_iomanager"
	@echo "... test_address"
	@echo "... test_http_server"
	@echo "... echo_server"
	@echo "... test_util"
	@echo "... test_config"
	@echo "... test_hook"
	@echo "... test_fiber"
	@echo "... test_scheduler"
	@echo "... deepblue/address.o"
	@echo "... deepblue/address.i"
	@echo "... deepblue/address.s"
	@echo "... deepblue/bytearray.o"
	@echo "... deepblue/bytearray.i"
	@echo "... deepblue/bytearray.s"
	@echo "... deepblue/config.o"
	@echo "... deepblue/config.i"
	@echo "... deepblue/config.s"
	@echo "... deepblue/env.o"
	@echo "... deepblue/env.i"
	@echo "... deepblue/env.s"
	@echo "... deepblue/fd_manager.o"
	@echo "... deepblue/fd_manager.i"
	@echo "... deepblue/fd_manager.s"
	@echo "... deepblue/fiber.o"
	@echo "... deepblue/fiber.i"
	@echo "... deepblue/fiber.s"
	@echo "... deepblue/hook.o"
	@echo "... deepblue/hook.i"
	@echo "... deepblue/hook.s"
	@echo "... deepblue/http/http.o"
	@echo "... deepblue/http/http.i"
	@echo "... deepblue/http/http.s"
	@echo "... deepblue/http/http_connection.o"
	@echo "... deepblue/http/http_connection.i"
	@echo "... deepblue/http/http_connection.s"
	@echo "... deepblue/http/http_parser.o"
	@echo "... deepblue/http/http_parser.i"
	@echo "... deepblue/http/http_parser.s"
	@echo "... deepblue/http/http_server.o"
	@echo "... deepblue/http/http_server.i"
	@echo "... deepblue/http/http_server.s"
	@echo "... deepblue/http/http_session.o"
	@echo "... deepblue/http/http_session.i"
	@echo "... deepblue/http/http_session.s"
	@echo "... deepblue/http/servlet.o"
	@echo "... deepblue/http/servlet.i"
	@echo "... deepblue/http/servlet.s"
	@echo "... deepblue/http/thirdparty/http_parser.o"
	@echo "... deepblue/http/thirdparty/http_parser.i"
	@echo "... deepblue/http/thirdparty/http_parser.s"
	@echo "... deepblue/iomanager.o"
	@echo "... deepblue/iomanager.i"
	@echo "... deepblue/iomanager.s"
	@echo "... deepblue/log.o"
	@echo "... deepblue/log.i"
	@echo "... deepblue/log.s"
	@echo "... deepblue/mutex.o"
	@echo "... deepblue/mutex.i"
	@echo "... deepblue/mutex.s"
	@echo "... deepblue/scheduler.o"
	@echo "... deepblue/scheduler.i"
	@echo "... deepblue/scheduler.s"
	@echo "... deepblue/socket.o"
	@echo "... deepblue/socket.i"
	@echo "... deepblue/socket.s"
	@echo "... deepblue/stream.o"
	@echo "... deepblue/stream.i"
	@echo "... deepblue/stream.s"
	@echo "... deepblue/streams/socket_stream.o"
	@echo "... deepblue/streams/socket_stream.i"
	@echo "... deepblue/streams/socket_stream.s"
	@echo "... deepblue/tcp_server.o"
	@echo "... deepblue/tcp_server.i"
	@echo "... deepblue/tcp_server.s"
	@echo "... deepblue/thread.o"
	@echo "... deepblue/thread.i"
	@echo "... deepblue/thread.s"
	@echo "... deepblue/timer.o"
	@echo "... deepblue/timer.i"
	@echo "... deepblue/timer.s"
	@echo "... deepblue/uri.o"
	@echo "... deepblue/uri.i"
	@echo "... deepblue/uri.s"
	@echo "... deepblue/util.o"
	@echo "... deepblue/util.i"
	@echo "... deepblue/util.s"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_node.o"
	@echo "... tests/test_node.i"
	@echo "... tests/test_node.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

