logs:
  - name: root
    level: info
    formatter: "%d%T%m%t%n"
    appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender
  - name: system
    level: info
    formatter: "%d%T%m%t%n"
    appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender
system:
  port: 9900
  value: 15
  int_vec:
    - 101
    - 201
  int_list: [10, 20, 30]
  int_set: [40, 40, 50, 60]
  int_uset: [40, 40, 50, 60]
  str_int_map:
    k1: 70
    k2: 80
    k3: 90
    k4: 100
  str_int_umap:
    k1: 70
    k2: 80
    k3: 90
    k4: 100

class:
  person:
    name: zhangy
    age: 18
    sex: true
  map:
    zhangy1:
      name: zhangy01
      age: 19
      sex: true
    zhangy2:
      name: zhangy02
      age: 20
      sex: false
  vec_map:
    k1:
      - name: zhangy03
        age: 21
        sex: true
      - name: zhangy04
        age: 22
        sex: false
    k2:
      - name: zhangy05
        age: 23
        sex: true
      - name: zhangy06
        age: 24
        sex: false
